[project]
name = "editor"
version = "0.1.0"
description = ""
main_script = "./src/main.py"

[packages]
QScintilla = "2.14.1"
PyQt5 = "5.15.10"
jedi = "0.19.1"

[scripts]
build-qrc = "pyrcc5 ./src/icons/resources.qrc -o ./src/resources.py"
upgrade-pip = "python -m pip install --upgrade pip"
